version: '3'
services:

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ${NGINX_CONFIG}:/etc/nginx/conf.d
    links:
      - radarr
      - jackett
      - transmission

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ${RADARR_CONFIG}:/config
      - ${MEDIA_DIR}:/media
    restart: unless-stopped
    links:
      - jackett
      - transmission

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ${JACKETT_CONFIG}:/config
      - ${MEDIA_DIR}:/media
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    ports:
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - ${TRANSMISSION_CONFIG}:/config
      - ${MEDIA_DIR}:/media

  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SUBDOMAINS=${DUCKDNS_DOMAINS}
      - TOKEN=${DUCKDNS_TOKEN}
    restart: unless-stopped
